### PR TITLE
Create form

### PR DESCRIPTION
**Pull request by sodabarauf**
this repository is about survey form which I create a survey form about natural resources pollution, that today is more important than ever in resources world, and I want to survey about ideas of people in this part.
in this pull request I did these things:
-I created repository, added development branch as default, added feature branch, worked on feature branch, namely followed GITHUB flow work.
-I created HTML file and CSS file also link them.
-I added a title with the name survey form.
-I added h1 tags.
-I added paragraph and form tag.
-I added label tags and input tags for name, last name, email, address, and contact number.
-I added select tag and option tags for education level.
-I added label tag and input tag for an idea about pollution.
-I added text area tag for comment.
-I added input tag with checkbox type.
-I added some <br> for break between lines.
-I added some styles and properties for my survey-form.html.
-I added linters.

### CODE REVIEW

**Comment by ahzamir** [comment]
### Hi @sodabarauf 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by sodabarauf** [comment]
**HI@ahzamir**
 sir thanks from your feedback,
 again, I worked on this form made some changes to HTML and CSS files according survey form of freecode camp.org, also I checked my codes. I hope this be acceptable.

**Comment by ahzamir** [comment]
> **HI@ahzamir** sir thanks from your feedback, again, I worked on this form made some changes to HTML and CSS files according survey form of freecode camp.org, also I checked my codes. I hope this be acceptable.

Well Done @sodabarauf ,

But still, your .html files do not pass all checks in the freecodecamp `Survey Form` project

**Comment by sodabarauf** [comment]
@ahzamir 
sir I solved the errors and freecodecamp passed all codes, may be acceptable.

**Comment by ahzamir** [comment]
### Hi @sodabarauf 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
